[package]
edition = "2024"
name = "interrupt"
version = "0.1.0"
authors = ["Michael Schöttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>, Lukas Rose <public@lrose.de>"]

[dependencies]
# External depencies
num_enum = { version = "0.7", default-features = false }
bitflags = "1.0"
syscall = { path = "../syscall" }
terminal = { path = "../terminal" }
