[workspace]
resolver = "2"

members = [
    "os/kernel",
    "os/application/hello",
    "os/application/helloc",
    "os/application/shell",
    "os/application/uptime",
    "os/application/date",
    "os/application/mkdir",
    "os/application/meltdown",
]

# [profile.release]
# debug = true
